AWSTemplateFormatVersion: 2010-09-09
Description: roman-project
Resources:
  RomanSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Roman security group #required
      GroupName: romansecgroup
     
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        
      Tags:
        - Key: SecurityGroup 
          Value: SecurityGroup
        
      
  RomanProject:
    Type: AWS::EC2::Instance
    Properties:
     
      ImageId: ami-0742b4e673072066f
    
      InstanceType: t2.micro
      
      KeyName: Firstkey
      
      SecurityGroupIds:
        - !Ref RomanSecGroup
      
      
     
      UserData: 
        Fn::Base64:
        
          #! /bin/bash

          yum update -y

          yum install python3 -y

          pip3 install flask

          wget https://raw.githubusercontent.com/BurcuSevgican/aws-devops/main/aws/projects/Project-001-Roman-Numerals-Converter/app.py
          mkdir templates

          cd templates

          wget https://raw.githubusercontent.com/BurcuSevgican/aws-devops/main/aws/projects/Project-001-Roman-Numerals-Converter/templates/index.html

          wget https://raw.githubusercontent.com/BurcuSevgican/aws-devops/main/aws/projects/Project-001-Roman-Numerals-Converter/templates/number.html
          cd ..
          python3 app.py
      
